import { CVData } from './types';

export const defaultCVData: CVData = {
  personalInfo: {
    name: "Jamel Alhamd",
    title: "Full-Stack Developer | React · Node.js · AI Automation",
    email: "j_hamad83@hotmail.com",
    phone: "0176 82216044",
    address: "Bad Driburg, 33014",
    github: "https://github.com/jamelalhamd",
    linkedin: "https://linkedin.com/in/jamel-alhamd",
    photoUrl: "",
    bio: "Technisch vielseitiger Full-Stack-Entwickler mit Informatikstudium, 3+ Jahren Freelance-Erfahrung sowie laufender Umschulung zum Fachinformatiker für Anwendungsentwicklung (IHK) bei Swoppen GmbH Paderborn (08/2025 – 07/2027). Spezialisiert auf React/Node.js, MongoDB und KI-gestützte Workflow-Automatisierung mit Claude Code & n8n. Mehrsprachig (Arabisch, Deutsch B2, Englisch B2).",
  },
  experiences: [
    {
      id: "1",
      company: "Swoppen GmbH, Paderborn",
      position: "Fachinformatiker AE — Umschulung (IHK)",
      startDate: "2025-08",
      endDate: "2027-07",
      description: "2-jährige staatlich anerkannte Umschulung, Schwerpunkt Full-Stack-Entwicklung. React.js, Node.js, MongoDB, REST APIs in praxisnahen Projekten. Claude Code & KI-Agenten zur Automatisierung von Entwicklungsworkflows. n8n-Automatisierungspipelines und Cloud-Prototyping auf Replit.",
    },
    {
      id: "2",
      company: "Selbstständig",
      position: "Web- & Mobilentwickler (Freelance)",
      startDate: "2018-01",
      endDate: "2021-12",
      description: "8+ Kundenprojekte mit React.js, Flutter, Laravel, PHP erfolgreich geliefert. REST-API-Integrationen, responsive SPAs, direkte Kundenbetreuung.",
    },
    {
      id: "3",
      company: "Petroleum Company Abu Dhabi / Syrian Petroleum",
      position: "Maschinenführer & Elektriker",
      startDate: "2004-01",
      endDate: "2017-12",
      description: "Betrieb und Wartung industrieller Anlagen und Automationssysteme.",
    },
    {
      id: "4",
      company: "Projekt: FreshMart – Supermarkt-Webapp",
      position: "Full-Stack Entwickler",
      startDate: "2024-01",
      endDate: "2024-12",
      description: "React.js · Node.js · MongoDB · REST API. Full-Stack E-Commerce mit 8 Seiten, Admin-Dashboard, Suchfunktion und Drei-Schichten-Architektur.",
    },
    {
      id: "5",
      company: "Projekt: Schulverwaltung",
      position: "Datenbankentwickler",
      startDate: "2024-01",
      endDate: "2024-06",
      description: "SQL · MySQL · UML · ERD · HTML/CSS. Normalisiertes DB-Schema mit interaktivem HTML-ERD/UML-Viewer und vollständiger Projektdokumentation.",
    },
    {
      id: "6",
      company: "Projekt: FitLang – Fitness-Programmiersprache",
      position: "Interpreter-Entwickler",
      startDate: "2024-06",
      endDate: "2024-12",
      description: "JavaScript · Interpreter-Design · DSL. Eigene domänenspezifische Sprache mit Fitness-Vokabular, vollständigem Parser und Evaluator.",
    },
  ],
  skills: [
    { id: "1", name: "React.js / Next.js", level: 90 },
    { id: "2", name: "Node.js", level: 85 },
    { id: "3", name: "Flutter / Dart", level: 75 },
    { id: "4", name: "HTML5 / CSS3 / Tailwind", level: 90 },
    { id: "5", name: "Laravel / PHP", level: 75 },
    { id: "6", name: "C# / Java", level: 65 },
    { id: "7", name: "MongoDB / MySQL / SQL", level: 85 },
    { id: "8", name: "Git / GitHub / REST APIs", level: 90 },
    { id: "9", name: "Claude Code / AI Agents", level: 80 },
    { id: "10", name: "n8n Automation / Replit", level: 75 },
  ],
  languages: [
    { id: "1", name: "Arabisch", level: "native" },
    { id: "2", name: "Deutsch", level: "intermediate" },
    { id: "3", name: "Englisch", level: "intermediate" },
  ],
  certificates: [
    {
      id: "1",
      name: "Fachinformatiker für Anwendungsentwicklung (IHK)",
      issuer: "Swoppen GmbH / IHK",
      date: "2027-07",
      description: "2-jährige staatlich anerkannte Umschulung zum Fachinformatiker für Anwendungsentwicklung, Schwerpunkt Full-Stack-Entwicklung.",
      fileUrl: "",
      fileName: "",
    },
    {
      id: "2",
      name: "B.Sc. Informatik",
      issuer: "Syrian Virtual University",
      date: "2018-06",
      description: "Bachelor of Science in Informatik, Abschluss an der Syrian Virtual University (2013–2018).",
      fileUrl: "",
      fileName: "",
    },
    {
      id: "3",
      name: "B.A. Anglistik",
      issuer: "Universität al-Baath",
      date: "2008-06",
      description: "Bachelor of Arts in Anglistik, Abschluss an der Universität al-Baath (2004–2008).",
      fileUrl: "",
      fileName: "",
    },
  ],
};
